on:
  workflow_dispatch:
  push:
    branches: [ master, add/gh-action-prod ]

name: Deploy Production CGK
jobs:
  build:
    name: Build
    runs-on: [self-hosted, eks-runner]
    outputs:
      image_registry: ${{ steps.publish_image.outputs.image_registry }}
      image_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Create Version Tagging 
        id: version
        uses: codacy/git-version@2.4.0
        with:
          prefix: "v"
      
      - name : Use the Version
        run: |
          echo ${{ steps.version.outputs.version }}
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.version }}

      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}

      - name: Push Tagging
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.version.outputs.version }}',
            sha: context.sha
            })
      
      - name: Checkout
        uses: actions/checkout@v2
